# Generated by Django 5.2.3 on 2025-06-16 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WellsStatuses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Имя статуса",
                    ),
                ),
                (
                    "guid_1c",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="ИД статуса в 1C",
                    ),
                ),
                (
                    "alt_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Псевдоним"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статусы скважин",
                "verbose_name_plural": "Статусы скважин",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Отметка времени создания объекта",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Отметка времени изменения объекта",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Сокращенное наименование",
                    ),
                ),
                (
                    "alt_name",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Псевдоним"
                    ),
                ),
                (
                    "name_1c",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Имя в 1с"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, создавший запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участок недр",
                "verbose_name_plural": "Участки недр",
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Отметка времени создания объекта",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Отметка времени изменения объекта",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Сокращенное наименование",
                    ),
                ),
                (
                    "alt_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Псевдоним"
                    ),
                ),
                (
                    "name_1c",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Имя в 1с"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, создавший запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Месторождение",
                "verbose_name_plural": "Месторождения",
            },
        ),
        migrations.CreateModel(
            name="Pad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Отметка времени создания объекта",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Отметка времени изменения объекта",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "create_date",
                    models.DateField(auto_now=True, verbose_name="Дата создания"),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Флаг удаления"
                    ),
                ),
                (
                    "is_numberless",
                    models.BooleanField(
                        default=False, verbose_name="Признак безномерного куста"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, создавший запись",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wells.field",
                        verbose_name="Месторождение",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wells.district",
                        verbose_name="Участок недр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кустовая площака",
                "verbose_name_plural": "Кустовые площадки",
            },
        ),
        migrations.CreateModel(
            name="Well",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Отметка времени создания объекта",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Отметка времени изменения объекта",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Имя скважины"
                    ),
                ),
                (
                    "is_numberless",
                    models.BooleanField(
                        default=False, verbose_name="Признак безномерной скважины"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, создавший запись",
                    ),
                ),
                (
                    "wellpad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wells.pad",
                        verbose_name="Кустовая площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скважина",
                "verbose_name_plural": "Скважины",
            },
        ),
        migrations.CreateModel(
            name="WellsStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Отметка времени создания объекта",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Отметка времени изменения объекта",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Имя статуса скважины"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#ffffffff", max_length=255, verbose_name="Цвет"
                    ),
                ),
                (
                    "fund",
                    models.IntegerField(
                        choices=[
                            (0, "ВДЗ"),
                            (1, "ВЗ"),
                            (2, "ГД"),
                            (3, "ГН"),
                            (4, "НД"),
                            (5, "НН"),
                            (6, "ПОГЛ"),
                            (7, "РД"),
                            (8, "РН"),
                        ],
                        default=4,
                    ),
                ),
                (
                    "is_actual",
                    models.BooleanField(
                        default=True, verbose_name="Актуален статус скважины или нет"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, создавший запись",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wells.wellsstatuses",
                        verbose_name="Состояние скважины",
                    ),
                ),
            ],
            options={
                "verbose_name": "Справочник по статусам скважин",
                "verbose_name_plural": "Справочник по статусам скважин",
            },
        ),
        migrations.CreateModel(
            name="WellsBaseFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Отметка времени создания объекта",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Отметка времени изменения объекта",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата состояния")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, создавший запись",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wells.well",
                        verbose_name="Ссылка на скважину",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wells.wellsstatus",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фонд ИНК",
                "verbose_name_plural": "Фонд ИНК",
            },
        ),
        migrations.AddConstraint(
            model_name="pad",
            constraint=models.UniqueConstraint(
                fields=("name", "field", "license"), name="unique_pad_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="wellsbasefund",
            constraint=models.UniqueConstraint(
                fields=("date", "well"), name="unique_date_well"
            ),
        ),
        migrations.AddConstraint(
            model_name="wellsstatus",
            constraint=models.UniqueConstraint(
                fields=("name", "fund"), name="unique_name_fund"
            ),
        ),
    ]
