# Generated by Django 5.2.3 on 2025-06-16 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wells", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacteristicBaseFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Отметка времени создания объекта",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Отметка времени изменения объекта",
                    ),
                ),
                ("area", models.CharField(null=True, verbose_name="Площадь")),
                (
                    "delay_period",
                    models.DateField(
                        null=True, verbose_name="Срок временной приостановки"
                    ),
                ),
                (
                    "delay_start",
                    models.DateField(
                        null=True, verbose_name="Дата начала временной приостановки"
                    ),
                ),
                (
                    "building_end_date",
                    models.DateField(
                        null=True, verbose_name="Дата окончания строительста"
                    ),
                ),
                (
                    "building_end_date_zbs",
                    models.DateField(
                        null=True, verbose_name="Дата окончания строительста ЗБС"
                    ),
                ),
                (
                    "conservation_date_fact",
                    models.DateField(
                        null=True,
                        verbose_name="Дата начала фактической консвервации / ликвидации ",
                    ),
                ),
                (
                    "conservation_date_start",
                    models.DateField(
                        null=True,
                        verbose_name="Дата начала консервации / ликвидации (РТН)",
                    ),
                ),
                (
                    "conservation_date_end",
                    models.DateField(
                        null=True,
                        verbose_name="Дата окончания консервации / ликвидации (РТН)",
                    ),
                ),
                (
                    "delay_comment",
                    models.TextField(
                        null=True,
                        verbose_name="Комментарий по сроку временной приостановки",
                    ),
                ),
                (
                    "conservation_comment",
                    models.TextField(
                        null=True, verbose_name="Комментарий для консервации"
                    ),
                ),
                (
                    "inspection_date_fact",
                    models.DateField(null=True, verbose_name="Дата осмотра (факт)"),
                ),
                (
                    "inspection_date_chart",
                    models.DateField(null=True, verbose_name="Дата осмотра (график)"),
                ),
                (
                    "inspection_date_next_year",
                    models.DateField(
                        null=True, verbose_name="Дата осмотра в следующем году"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, создавший запись",
                    ),
                ),
                (
                    "original_well",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_original_well",
                        to="wells.well",
                        verbose_name="Первоначальный номер скважины",
                    ),
                ),
                (
                    "well",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_well",
                        to="wells.well",
                        verbose_name="Ссылка на скважину",
                    ),
                ),
            ],
            options={
                "verbose_name": "Постоянные характеристики",
                "verbose_name_plural": "Постоянные характеристики",
            },
        ),
    ]
