# Generated by Django 5.2.3 on 2025-06-16 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GSIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Отметка времени создания объекта",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Отметка времени изменения объекта",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, создавший запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Показатель",
                "verbose_name_plural": "Показатели",
            },
        ),
        migrations.CreateModel(
            name="GSInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Отметка времени создания объекта",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Отметка времени изменения объекта",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, создавший запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Установка",
                "verbose_name_plural": "Установки",
            },
        ),
        migrations.CreateModel(
            name="GSTypePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Отметка времени создания объекта",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Отметка времени изменения объекта",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, создавший запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип плана",
                "verbose_name_plural": "Типы плана",
            },
        ),
        migrations.CreateModel(
            name="GSProductionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Отметка времени создания объекта",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Отметка времени изменения объекта",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата, первое число месяца")),
                (
                    "value",
                    models.FloatField(
                        null=True, verbose_name="Значение выработки продукции"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, создавший запись",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_product_indicator",
                        to="gas_service.gsindicator",
                        verbose_name="Показатель",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_product_installation",
                        to="gas_service.gsinstallation",
                        verbose_name="Установка",
                    ),
                ),
                (
                    "type_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_product_type_plan",
                        to="gas_service.gstypeplan",
                        verbose_name="Тип плана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выработка продукции",
                "verbose_name_plural": "Выработки продукции",
            },
        ),
    ]
